services:
  db:
    build:
      context: db
      dockerfile: Dockerfile
    container_name: db-c
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - net

  eureka-server:
    build:
      context: eureka server/eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server-c
    expose:
      - "8070"
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - net

  user-service:
    build:
      context: user service/user-service
      dockerfile: Dockerfile
    container_name: user-service-c
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - net
    depends_on:
      - eureka-server
      - db
      
  
  workouts-service:
    build:
      context: workouts-service
      dockerfile: Dockerfile
    container_name: workouts-service-c
    expose:
      - "8081"
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - net
    depends_on:
      - eureka-server
      - db
      
  
  stats-service:
    build:
      context: stats-service
      dockerfile: Dockerfile
    container_name: stats-service-c
    expose:
      - "8084"
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - net
    depends_on:
      - eureka-server
      - db
      

  plans-service:
    build:
      context: plans service/plans-service
      dockerfile: Dockerfile
    container_name: plans-service-c
    expose:
      - "8082"
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - net
    depends_on:
      - eureka-server
      - db
      

  gateway-service:
    build:
      context: gateway/gateway
      dockerfile: Dockerfile
    container_name: gateway-service-c
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - net
    depends_on:
      - db
      - user-service
      - plans-service
      - workouts-service
      - stats-service
      - eureka-server
    restart: on-failure

networks:
  net:
    driver: bridge