server:
  port: 8080
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://db:5432/userData
    username: postgres
    password: pass123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/
    fetch-registry: true
    register-with-eureka: true

